### ISSUE TITLE
TypeLoadException in SqlServerHierarchyIdMethodTranslator with EF Core 5.0.0-rc.1

### ISSUE THREAD

**Issue by vyrotek** [efcore/EFCore.SqlServer.HierarchyId#26]
I was experimenting with updating our app to use EF Core 5.0.0-rc.1.20451.13 but got this exception from the DbContext.

> System.TypeLoadException: 'Method 'Translate' in type 'Microsoft.EntityFrameworkCore.SqlServer.Query.ExpressionTranslators.SqlServerHierarchyIdMethodTranslator' from assembly 'EntityFrameworkCore.SqlServer.HierarchyId, Version=1.1.0.0, Culture=neutral, PublicKeyToken=0c30ba8633cb7b1e' does not have an implementation.'

I'm not quite sure what other info I can provide to help. :)

**Comment by bricelam** [comment]
I think Smit was anticipating this when he filed #16 🙂 I'll try to do an rc1 release this weekend.

**Comment by bricelam** [comment]
Broken by dotnet/efcore#21935.

@roji I think going forward, I'd like to support both the latest LTS and the latest Current release of EF Core. If that can be done using a single NuGet package, great! Otherwise, we'll start doing parallel releases until the next LTS release of EF Core. I don't think I want to keep the major version number in sync with EF Core, but rather just bump it whenever this library needs to make a breaking change (either because of EF Core or otherwise). Thoughts?

**Comment by bricelam** [comment]
lol, and I know I probably sound like a completely different person when talking about the strategy for our community-driven libraries. 😉

**Comment by smitpatel** [comment]
I would prefer non-alignment of versions with EF Core as long as we are semver. 
We made break here so 3.1/5.0 via single package would be difficult. In future we can just leave package as is if there were no breaks.

For 3.1/5.0 break, what if we implement Translate method from both versions? They come from interface so will be not be overriden. Compiler should not generate above error like that there is no implementation if we add both implementations.

**Comment by bricelam** [comment]
Current plan:
* Release a new 1.1.1 version setting an upper bound on EF Core dependency
* Upgrade to EF Core 5.0 RC1 and release a new 2.0 prerelease version
* As needed, create a `release-1.x` branch to backport any features and fixes for EF Core 3.1
